ALTER TABLE "Course" ADD COLUMN "tagsJson" TEXT;
ALTER TABLE "Course" ADD COLUMN "thumbnailUrl" TEXT;
ALTER TABLE "Course" ADD COLUMN "completionMode" TEXT NOT NULL DEFAULT 'ALL_ITEMS';
ALTER TABLE "Course" ADD COLUMN "statusFormat" TEXT NOT NULL DEFAULT 'COMPLETED_ONLY';
ALTER TABLE "Course" ADD COLUMN "gradedItemIdsJson" TEXT;
